name: 'Frontend Build'
description: 'Frontend Build Github Action'
author: 'Damian Sloane <damian.sloane@eonx.com>'
inputs:
  path:
    description: 'Path to the package to be deployed relative to the repository root'
    required: false
    default: ""
  environment:
    description: 'Environment code, this should be lowercase and hyphenated (e.g. "dev", "staging", "prod")'
    required: true
  npm_token:
    description: 'GitHub packages access token'
    default: ""
    required: false
  revision_file_location:
    description: 'Relative path for creation of a revision.txt file with the commit hash'
    default: "./dist/revision.txt"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
